"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Comprehensive inline translations
const translations = {
  en: {
    navigation: {
      home: "Home",
      products: "Products",
      digitalProducts: "Digital Products",
      services: "Services",
      aiStudio: "AI Studio",
      about: "About",
      contact: "Contact",
      signIn: "Sign In",
      signOut: "Sign Out",
      getStarted: "Get Started",
      dashboard: "Dashboard",
      orders: "Orders",
      downloads: "Downloads",
      digitalDownloads: "Digital Downloads",
      settings: "Settings",
      admin: "Admin",
      cart: "Cart",
      checkout: "Checkout",
      supplierPortal: "Supplier Portal",
    },
    cart: {
      title: "Your Cart",
      empty: "Your cart is empty",
      emptyDescription: "Add some products to your cart to get started",
      browseProducts: "Browse Products",
      proceedToCheckout: "Proceed to Checkout",
      items: "items",
      removeItem: "Remove item",
      updateQuantity: "Update quantity",
      subtotal: "Subtotal",
    },
    products: {
      title: "Products",
      description: "Discover our wide range of custom printing products",
      catalogTitle: "Product Catalog",
      catalogDescription: "Browse our collection of customizable products",
      searchPlaceholder: "Search products...",
      allCategories: "All Categories",
      sortBy: "Sort by",
      sortName: "Name",
      sortPriceAsc: "Price: Low to High",
      sortPriceDesc: "Price: High to Low",
      sortNewest: "Newest",
      badgeCustomizable: "Customizable",
      buttonCustomize: "Customize",
      noProductsFound: "No products found matching your criteria",
    },
    productDetail: {
      notFoundTitle: "Product not found",
      notFoundDescription:
        "The product you're looking for doesn't exist or has been removed.",
      backToProducts: "Back to Products",
      quantity: "Quantity",
      size: "Size",
      addToCart: "Add to Cart",
      save: "Save",
      // Toast wording for successful save on product page
      saveSuccess: "Item saved",
      saveSuccessDesc: "Saved to your library.",
      share: "Share",
      tabDetails: "Product Details",
      tabCustomize: "Customize Design",
      specificationsTitle: "Product Specifications",
      materialLabel: "Material:",
      materialValue: "Premium Quality",
      dimensionsLabel: "Dimensions:",
      dimensionsValue: "Varies by size",
      printAreaLabel: "Print Area:",
      printAreaValue: "Front and back",
      careLabel: "Care:",
      careValue: "Machine washable",
      shippingInfoTitle: "Shipping Information",
      productionTimeLabel: "Production Time:",
      productionTimeValue: "2-3 business days",
      shippingLabel: "Shipping:",
      shippingValue: "3-5 business days",
      returnsLabel: "Returns:",
      returnsValue: "30-day return policy",
    },
    checkout: {
      title: "Checkout",
      subtitle: "Complete your order by providing your information below",
      digitalOrderTitle: "Digital Products Order",
      digitalOrderBadge: "Digital Download",
      digitalOrderDescription:
        "Your digital products will be available for download after payment is complete.",
      completePaymentWithPayPal: "Complete Payment with PayPal",
      clickPayPalButtons:
        "Click one of the PayPal buttons below to complete your payment",
      orderTotal: "Order Total:",
      orderNumberLabel: "Order #",
      backToCheckout: "Back to Checkout",
      billingTitle: "Billing Information",
      billingDescription: "Please enter your billing details",
      shippingTitle: "Shipping Information",
      shippingDescription: "Where should we send your order?",
      sameAsBilling: "Same as billing address",
      firstName: "First Name *",
      lastName: "Last Name *",
      email: "Email Address *",
      phone: "Phone Number *",
      address: "Street Address *",
      city: "City *",
      state: "State/Province *",
      zipCode: "Postal/Zip Code *",
      country: "Country *",
      orderNotesLabel: "Order Notes (Optional)",
      orderNotesPlaceholder: "Special instructions for delivery or order details...",
      deliveryMethodTitle: "Delivery Method",
      deliveryMethodDescription: "Choose how you want your order delivered",
      paymentMethodTitle: "Payment Method",
      paymentMethodDescription: "Select how you want to pay for your order",
      orderSummaryTitle: "Order Summary",
      orderSummaryDescription: "Review your order before checking out",
      subtotalLabel: "Subtotal",
      shippingLabel: "Shipping",
      taxLabel: "Tax (13%)",
      totalLabel: "Total",
      agreeToTerms: "I agree to the Terms of Service and Privacy Policy",
      completeOrder: "Complete Order",
      paymentMethods: {
        wompi: { name: "Credit/Debit Card", description: "Visa, Mastercard, American Express" },
        paypal: { name: "PayPal", description: "PayPal Account" },
        stripe: { name: "Stripe", description: "Credit/Debit Card" },
        cash: { name: "Cash on Delivery", description: "Pay when you receive" },
      },
      shippingMethods: {
        standard: { name: "Regular Shipping", description: "5-7 business days" },
        express: { name: "Priority Shipping", description: "3-5 business days" },
        overnight: { name: "Urgent Shipping", description: "1-2 business days" },
        pickup: { name: "Store Pickup", description: "Pick up at our store" },
        download: { name: "Digital Download", description: "Instant download after payment" },
      },
    },
    home: {
      heroTitle: "Your Vision, Printed.",
      heroSubtitle:
        "High-quality custom printing for all your needs. From apparel to large format, we bring your ideas to life.",
      exploreProducts: "Explore Products",
      servicesTitle: "Our Services",
      featuredProductsTitle: "Featured Products",
      // Bottom CTA on Home page
      ctaTitle: "Ready to Print Your Ideas?",
      ctaSubtitle:
        "Get started with our easy-to-use design tools or contact us for a custom quote.",
      ctaGetQuote: "Get a Quote",
      errors: {
        failedToLoadFeatured: "Failed to load featured products. Please try again later.",
        displayingSample: "Displaying sample products instead.",
      },
      noFeatured: "No featured products found. Displaying sample products.",
      noDescription: "No description available.",
    },
    orders: {
      title: "Orders",
      myOrders: "My Orders",
    },
    dashboard: {
      title: "Dashboard",
    },
    settings: {
      title: "Settings",
    },
    services: {
      all: "All Services",
      digitalPrinting: "Digital Printing",
      largeFormat: "Large Format",
      eventStands: "Event Stands",
      illuminatedSigns: "Illuminated Signs",
      designStudio: "Design Studio",
      digitalPrintingDesc: "High-resolution prints for brochures, flyers, and custom designs.",
      largeFormatDesc: "Banners, posters, and signs for maximum impact.",
      designStudioDesc: "Create stunning designs with our AI-powered tools or professional help.",
      page: {
        heroTitle: "Professional Printing Services",
        heroSubtitle: "Complete printing solutions for your business needs - from digital printing to illuminated signage",
        ctaGetStarted: "Get Started",
        ctaRequestQuote: "Request Quote",
        sectionTitle: "Our Services",
        sectionSubtitle: "Choose from our comprehensive range of printing services, each designed to meet specific business needs",
        featuresLabel: "Features:",
        startingFrom: "Starting from",
        explore: "Explore",
        whyChooseTitle: "Why Choose Our Services?",
        whyChooseSubtitle: "We're committed to delivering exceptional quality and service for all your printing needs",
        benefitQuality: "Quality Guarantee",
        benefitSpeed: "Fast Turnaround",
        benefitPro: "Professional Service",
        howItWorksTitle: "How It Works",
        howItWorksSubtitle: "Simple steps to get your printing project completed",
        steps: {
          chooseService: "Choose Service",
          descChooseService: "Select the printing service that fits your needs",
          configureUpload: "Configure & Upload",
          descConfigureUpload: "Customize options and upload your design files",
          reviewOrder: "Review & Order",
          descReviewOrder: "Review your order details and complete payment",
          productionDelivery: "Production & Delivery",
          descProductionDelivery: "We print and deliver your order on time",
        },
        ctaTitle: "Ready to Start Your Project?",
        ctaSubtitle: "Get professional printing services with fast turnaround times and competitive pricing",
        ctaStartDigitalPrinting: "Start Digital Printing",
        ctaRequestCustomQuote: "Request Custom Quote",
      },
      largeFormatPage: {
        headerTitle: "Large Format Printing",
        headerSubtitle: "Professional banners, posters, and specialty large-scale printing",
        customDesignReady: "Custom Design Ready for Printing",
        customDesignCardTitle: "Your Custom Design",
        manuallyCreated: "Manually Created",
        readyForPrinting: "Ready for Printing",
        selectProductType: "Select Product Type",
        weatherResistant: "Weather Resistant",
        baseLabel: "Base:",
        sizeConfigTitle: "Size Configuration",
        width: "Width",
        height: "Height",
        standardSize: "Standard size",
        totalArea: "Total Area",
        squareMeters: "square meters",
        quantity: "Quantity",
        specialInstructionsLabel: "Special Instructions (Optional)",
        specialInstructionsPlaceholder: "Grommets, hemming, mounting requirements, etc.",
        uploadCreateTitle: "Upload or Create Your Design",
        dropFilesHere: "Drop your files here",
        supportFormats: "Support: PDF, PNG, JPG, AI, PSD (Max 100MB)",
        chooseFiles: "Choose Files",
        orCreateCustomDesign: "Or create a custom design:",
        customizeDesign: "Customize Design",
        designLoaded: "Design Loaded",
        designReady: "Your custom design is ready.",
        editDesign: "Edit Design",
        guidelinesTitle: "Large Format Guidelines:",
        guidelines: {
          bullet1: "• Minimum 150 DPI at final size",
          bullet2: "• Vector files preferred for scalability",
          bullet3: "• Include bleed for edge-to-edge printing",
          bullet4: "• Consider viewing distance for text size",
        },
        orderSummaryTitle: "Order Summary",
        size: "Size:",
        area: "Area:",
        design: "Design:",
        custom: "Custom",
        unitPrice: "Unit Price:",
        areaCost: "Area Cost:",
        total: "Total:",
        requestDetailedQuote: "Request Detailed Quote",
        productionInfoTitle: "Production Info",
        turnaround: "Turnaround:",
        turnaroundValue: "2-3 business days",
        material: "Material:",
        materialValue: "13oz Vinyl",
        finishing: "Finishing:",
        finishingValue: "Grommets available",
        installation: "Installation:",
        installationValue: "Available",
        sqMetersShort: "sq m",
        products: {
          banner: {
            name: "BANNER",
            description: "Durable vinyl banners perfect for outdoor advertising and events",
            unit: "MTS",
            priceUnit: "per sq meter",
          },
          troquelados: {
            name: "TROQUELADOS",
            description: "Precision die-cut shapes and custom cutouts",
            unit: "inches",
            priceUnit: "per piece",
          },
        },
      },
      // Service-specific pages
       digitalPrintingPage: {
        headerTitle: "Digital Printing Services",
        headerSubtitle: "High-quality standard format printing for all your business needs",
        aiGeneratedLabel: "AI-Generated Design",
        customDesignLabel: "Custom Design",
        readyForPrinting: "Ready for Printing",
        yourAIGeneratedDesign: "Your AI-Generated Design",
        yourCustomDesign: "Your Custom Design",
        manuallyCreated: "Manually Created",
        selectMaterial: "Select Material",
        doubleSided: "Double-sided",
        sizeOptionsTitle: "Size & Options",
        materialSize: "Material Size",
        printSides: "Print Sides",
        singleSided: "Single-sided",
        quantity: "Quantity",
        uploadCreateTitle: "Upload or Create Your Design",
        dropFilesHere: "Drop your files here",
        supportFormatsShort: "Support: PDF, PNG, JPG, AI, PSD, ZIP (Max 50MB)",
        chooseFiles: "Choose Files",
        uploadedFilesLabel: "Uploaded Files:",
        orCreateCustomDesign: "Or create a custom design:",
        customizeDesign: "Customize Design",
        customUpload: "Custom Upload",
        designLoaded: "Design Loaded",
        designReady: "Your custom design is ready.",
        editDesign: "Edit Design",
        replace: "Replace",
        edit: "Edit",
        designGuidelinesTitle: "Design Guidelines:",
        guidelines: {
          bullet1: "• Minimum 300 DPI resolution",
          bullet2: "• Include 0.125\" bleed for full-coverage designs",
          bullet3: "• CMYK color mode preferred",
        },
        orderSummaryTitle: "Order Summary",
        aiGenerated: "AI Generated",
        requestCustomQuote: "Request Custom Quote",
        products: {
          "foldcote-14": {
            name: "FOLDCOTE 14",
            description: "Premium coated paper with excellent print quality and durability",
          },
          adhesivo: {
            name: "ADHESIVO",
            description: "High-quality vinyl stickers with strong adhesive backing",
          },
          couche: {
            name: "COUCHE",
            description: "Smooth coated paper perfect for high-quality color printing",
          },
          bond: {
            name: "BOND",
            description: "Standard office paper for everyday printing needs",
          },
          "etiqueta-especial": {
            name: "ETIQUETA ESPECIAL",
            description: "Premium specialty labels for professional applications",
          },
          vinyl: {
            name: "VINYL BANNER",
            description: "Durable vinyl material perfect for outdoor signage and large format printing",
          },
          troquelate: {
            name: "TROQUELATE",
            description: "Die-cut specialty material for custom shapes and professional applications",
          },
          canvas: {
            name: "CANVAS",
            description: "High-quality canvas material ideal for art prints and large format displays",
          },
        },
      },
      eventStandsPage: {
        headerTitle: "Event Stands & Displays",
        headerSubtitle:
          "Professional event displays, trade show booths, and portable stands to make your brand stand out at any event",
        badges: {
          freeShipping: "Free Shipping",
          quickTurnaround: "Quick Turnaround",
          qualityGuarantee: "Quality Guarantee",
        },
        categories: {
          displayStands: "Display Stands",
          bannerDisplays: "Banner Displays",
          tradeShow: "Trade Show",
          eventBackdrops: "Event Backdrops",
        },
        selectStandTitle: "Select Your Event Stand",
        selectStandDescription: "Choose from our professional event display solutions",
        productType: "Product Type",
        sizeConfig: "Size & Configuration",
        dimensions: "Dimensions:",
        quantity: "Quantity",
        designRequirements: "Design Requirements",
        designRequirementsPlaceholder:
          "Describe your design requirements, colors, logos, text, etc.",
        rushOrderLabel: "Rush Order (+50% fee)",
        featuresLabel: "Features:",
        orderSummaryTitle: "Order Summary",
        basePrice: "Base Price",
        rushOrderFee: "Rush Order Fee (50%)",
        total: "Total",
        buttons: {
          addToCart: "Add to Cart",
          customizeDesign: "Customize Design",
          getCustomQuote: "Get Custom Quote",
          needHelpQuote: "Need help? Get Event Quote",
        },
        products: {
          "popup-stands": {
            name: "Pop-up Stands",
            description:
              "Portable and easy-to-setup display stands perfect for trade shows and events",
            features: {
              item1: "Tool-free assembly",
              item2: "Lightweight aluminum frame",
              item3: "Carrying case included",
              item4: "Wrinkle-resistant fabric",
            },
          },
          "banner-stands": {
            name: "Banner Stands",
            description:
              "Retractable banner stands for professional presentations and marketing displays",
            features: {
              item1: "Retractable mechanism",
              item2: "Adjustable height",
              item3: "Padded carrying case",
              item4: "Easy graphic change",
            },
          },
          "trade-show-displays": {
            name: "Trade Show Displays",
            description: "Complete trade show booth solutions with modular components",
            features: {
              item1: "Modular design",
              item2: "LED lighting options",
              item3: "Storage compartments",
              item4: "Professional setup",
            },
          },
          "backdrop-stands": {
            name: "Backdrop Stands",
            description:
              "Step and repeat backdrops perfect for events, photo ops, and branding",
            features: {
              item1: "Telescopic frame",
              item2: "Wrinkle-free fabric",
              item3: "Easy assembly",
              item4: "Portable carrying case",
            },
          },
        },
      },
      illuminatedSignsPage: {
        headerTitle: "Illuminated Signs",
        headerSubtitle:
          "Professional illuminated signage solutions to make your business shine day and night with energy-efficient LED technology",
        badges: {
          energyEfficient: "Energy Efficient",
          highVisibility: "High Visibility",
          impact247: "24/7 Impact",
        },
        selectTitle: "Select Your Illuminated Sign",
        selectDescription: "Choose from our professional illuminated signage options",
        signType: "Sign Type",
        sizeConfig: "Size & Configuration",
        dimensions: "Dimensions:",
        quantity: "Quantity",
        colorPreference: "Color Preference",
        colorPreferencePlaceholder: "e.g., Warm White, Cool White, Red, Blue, etc.",
        designRequirements: "Design Requirements",
        designRequirementsPlaceholder: "Describe your text, logos, graphics, mounting requirements, etc.",
        installationLabel: "Professional Installation (+$200)",
        rushOrderLabel: "Rush Order (+50% fee)",
        featuresLabel: "Features:",
        products: {
          "led-channel-letters": {
            name: "LED Channel Letters",
            description:
              "Premium 3D illuminated letters with LED lighting for maximum visibility and impact",
            features: {
              item1: "3D dimensional letters",
              item2: "Energy-efficient LEDs",
              item3: "Weather-resistant",
              item4: "Custom colors available",
            },
            category: "Channel Letters",
            unit: "per letter",
          },
          "backlit-signs": {
            name: "Backlit Signs",
            description:
              "Professional backlit signs with even illumination for storefronts and businesses",
            features: {
              item1: "Even LED backlighting",
              item2: "Translucent face material",
              item3: "Aluminum frame",
              item4: "Easy installation",
            },
            category: "Backlit Signs",
            unit: "per sign",
          },
          "light-box-signs": {
            name: "Light Box Signs",
            description:
              "Traditional light box signs with modern LED technology for bright, uniform illumination",
            features: {
              item1: "LED light strips",
              item2: "Acrylic face",
              item3: "Snap-open frame",
              item4: "Wall or ceiling mount",
            },
            category: "Light Boxes",
            unit: "per sign",
          },
          "neon-style-led": {
            name: "Neon-style LED",
            description:
              "Modern LED neon strips that replicate traditional neon with energy efficiency",
            features: {
              item1: "Flexible LED strips",
              item2: "Multiple color options",
              item3: "Dimmable",
              item4: "Easy installation",
            },
            category: "LED Neon",
            unit: "per linear foot",
          },
          "digital-display-signs": {
            name: "Digital Display Signs",
            description:
              "High-resolution LED displays for dynamic content and maximum visual impact",
            features: {
              item1: "Full HD resolution",
              item2: "Remote content management",
              item3: "Weather-resistant options",
              item4: "Scheduling software",
            },
            category: "Digital Displays",
            unit: "per display",
          },
          "cabinet-signs": {
            name: "Cabinet Signs",
            description:
              "Illuminated cabinet signs with professional appearance for businesses and storefronts",
            features: {
              item1: "Aluminum construction",
              item2: "LED illumination",
              item3: "Translucent panels",
              item4: "Professional installation",
            },
            category: "Cabinet Signs",
            unit: "per sign",
          },
        },
      },
    },
    
    auth: {
      welcomeBack: "Welcome back",
      enterCredentials: "Enter your credentials to access your account",
      signIn: "Sign In",
      signOut: "Sign Out",
      getStarted: "Get Started",
      emailLabel: "Email",
      passwordLabel: "Password",
      forgotPassword: "Forgot password?",
      signingIn: "Signing you in...",
      createAccount: "Create account",
      noAccount: "Don't have an account?",
    },
    supplier: {
      portal: "Supplier Portal",
    },
    users: {
      title: "Users",
    },
    quotes: {
      title: "Quotes",
    },
    payment: {
      modal: {
        title: "Payment Details"
      },
      testMode: {
        title: "Test Mode",
        description: "Wompi test mode - Use CVV to simulate different scenarios:"
      },
      testCard: {
        declined: "Payment will be rejected",
        othersSuccess: "Payment will be successful",
        success: "Payment will be successful"
      },
      security: {
        sslEncrypted: "SSL Encrypted",
        pciCompliant: "PCI Compliant",
        notice: "Your payment information is secure and encrypted"
      },
      form: {
        cardNumber: "Card Number",
        month: "Month",
        year: "Year",
        cvv: "CVV",
        cardholderName: "Cardholder Name",
        country: "Country",
        region: "Region"
      },
      validation: {
        cardNumber: "Please enter a valid card number",
        expiry: "Please enter a valid expiry date",
        cvv: "Please enter a valid CVV",
        cardholderName: "Please enter the cardholder name",
      },
      summary: {
        totalToPay: "Total to Pay:"
      },
      processing: "Processing",
      payButton: "Pay",
      error: {
        title: "Payment Error",
        processingFailed: "Payment processing failed. Please try again."
      },
      success: {
        title: "Payment Successful",
        transactionId: "Transaction ID"
      },
      "3ds": {
        processing: {
          title: "Processing Payment",
          message: "Please wait while we verify your payment...",
        },
        success: {
          title: "Payment Successful!",
          message: "Your payment has been processed successfully.",
        },
        failed: {
          title: "Payment Failed",
          message: "Your payment could not be processed.",
        },
        error: {
          title: "Payment Error",
          message: "There was an error processing your payment.",
        },
        verifying: "Verifying payment with bank...",
        viewOrder: "View Order Details",
        viewAllOrders: "View All Orders",
        tryAgain: "Try Again",
        continueShopping: "Continue Shopping",
        transactionId: "Transaction ID",
      },
      errors: {
        insufficientFunds: "Insufficient funds in your account",
        declined: "Card declined by your bank",
        expiredCard: "Your card has expired",
        limitExceeded: "Transaction limit exceeded",
        restrictedCard: "Card is restricted",
        generic: "Payment failed. Please try again.",
      },
    },
    common: {
      loading: "Loading...",
      error: "Error",
      success: "Success",
      cancel: "Cancel",
      save: "Save",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      remove: "Remove",
      search: "Search",
      filter: "Filter",
      sort: "Sort",
      next: "Next",
      previous: "Previous",
      submit: "Submit",
      close: "Close",
      learnMore: "Learn More",
      startDesigning: "Start Designing",
      addToCart: "Add to Cart",
      labels: {
        size: "Size:",
        print: "Print:",
        quantity: "Quantity",
        design: "Design:",
        unitPrice: "Unit Price:",
        total: "Total:",
      },
      from: "From",
      quote: "Quote",
      ready: "Ready",
      loginRequired: {
        title: "Login Required",
        description: "Please log in to create custom designs.",
      },
      toast: {
        addedToCartTitle: "Added to Cart",
        addedToCartDescSuffix: "has been added to your cart.",
        designSavedTitle: "Design Saved",
        designSavedDesc: "Your custom design has been saved and will be applied to your order.",
      },
    },
    admin: {
      nav: {
        dashboard: "Dashboard",
        products: "Products",
        orders: "Orders",
        payments: "Payments",
        transactions: "Payment Transactions",
        users: "Users",
        quotes: "Quotes",
        messages: "Messages",
        translations: "Translations",
        settings: "Settings",
        emailSettings: "Email Settings",
      },
      // Descriptions for admin navigation items
      navDescriptions: {
        dashboard: "Overview of your system",
        products: "Manage your products",
        orders: "View and manage orders",
        payments: "Payment processors & transactions",
        transactions: "View all payment transactions",
        users: "Manage customers",
        quotes: "Manage quote requests",
        messages: "Customer support tickets",
        translations: "Review and manage UI translations",
        settings: "Configure system settings",
        emailSettings: "Configure email providers & templates",
      },
      layout: {
        panelTitle: "Admin Panel",
        accessDeniedTitle: "Access Denied",
        accessDeniedDesc: "You don't have permission to access the admin panel.",
        goToDashboard: "Go to Dashboard",
        backToSite: "Back to Site",
        account: "Account",
        myAccount: "My Account",
        signOut: "Sign Out",
      },
      dashboard: {
        headerTitle: "Dashboard",
        headerSubtitle: "Welcome to the DeliveryPrint admin panel",
        statCards: {
          totalRevenue: "Total Revenue",
          totalOrders: "Total Orders",
          totalUsers: "Total Users",
          totalProducts: "Total Products",
        },
        quickStats: {
          pendingOrders: "Pending Orders",
          completedOrders: "Completed Orders",
          pendingQuotes: "Pending Quotes",
          activeUsers: "Active Users",
        },
      },
      products: {
        headerTitle: "Product Management",
        headerDescription: "Manage your product catalog",
        searchPlaceholder: "Search products...",
        filterByCategory: "Filter by category",
        allCategories: "All Categories",
        title: "Products",
        tableDescription: "Manage your product inventory",
        table: {
          product: "Product",
          category: "Category",
          price: "Price",
          status: "Status",
          created: "Created",
          actions: "Actions",
        },
        aria: {
          selectAll: "Select all products",
          selectProduct: "Select product {name}",
        },
        labels: {
          featured: "Featured",
        },
        statuses: {
          active: "Active",
          inactive: "Inactive",
        },
        na: "—",
        importDialog: {
          triggerLabel: "Import",
          title: "Import Products from CSV",
          description: "Upload a CSV file to create or update products.",
          csvFileLabel: "CSV File",
          uploadButton: "Upload CSV",
          csvGuidelines:
            "Your CSV should contain columns like `id` (optional for updates), `name`, `description`, `price`, `category`, `image`, `is_active` (true/false), `is_featured` (true/false).",
        },
        exportMenu: {
          triggerLabel: "Export",
          exportAll: "Export All Products",
          exportSelectedWithCount: "Export Selected ({count})",
        },
        addButtonLabel: "Add Product",
        editDialog: {
          titleEdit: "Edit Product",
          titleAddNew: "Add New Product",
          descEdit: "Update product information",
          descAddNew: "Create a new product for your catalog",
          buttons: {
            update: "Update Product",
            create: "Create Product",
          },
        },
        form: {
          imageLabel: "Product Image",
          imageUrlLabel: "Image URL",
          imageUrlPlaceholder: "https://example.com/image.jpg",
          productNameLabel: "Product Name *",
          priceLabel: "Price *",
          descriptionLabel: "Description",
          categoryLabel: "Category",
          categoryPlaceholder: "e.g., Apparel, Accessories",
          activeLabel: "Active",
          featuredLabel: "Featured",
          imageSelectedInfo:
            "Image will be uploaded from selected file. Manual URL input disabled.",
        },
        imageUpload: {
          clickToUpload: "Click to upload",
          orDragAndDrop: "or drag and drop",
          supportedFormats: "SVG, PNG, JPG or GIF (MAX. 800x400px)",
          removeImage: "Remove Image",
          previewAlt: "Product Preview",
          uploading: "Uploading Image...",
        },
        toasts: {
          errorLoadingProducts: "Failed to load products",
          imageUploadedTitle: "Image Uploaded",
          imageUploadedDesc: "Product image uploaded successfully.",
          imageUploadFailedTitle: "Image Upload Failed",
          imageUploadFailedDesc: "An error occurred during image upload.",
          submissionFailedTitle: "Submission Failed",
          submissionFailedDesc: "Image upload failed, please try again.",
          productUpdated: "Product updated successfully",
          productCreated: "Product created successfully",
          saveProductFailed: "Failed to save product",
          deleteConfirm: "Are you sure you want to delete this product?",
          productDeleted: "Product deleted successfully",
          deleteProductFailed: "Failed to delete product",
          noFileSelectedTitle: "No file selected",
          noFileSelectedDesc: "Please select a CSV file to import.",
          importingProductsTitle: "Importing Products",
          importingProductsDesc: "Uploading and processing your CSV file...",
          importCompleteTitle: "Import Complete",
          importCompleteDesc:
            "Successfully imported {created} new products and updated {updated} existing products.",
          importFailedTitle: "Import Failed",
          importFailedDesc: "An error occurred during product import.",
          exportingProductsTitle: "Exporting Products",
          exportingProductsDesc: "Preparing your product data for download...",
          noProductsSelectedTitle: "No Products Selected",
          noProductsSelectedDesc:
            "Please select products to export, or choose \"Export All\".",
          exportCompleteTitle: "Export Complete",
          exportCompleteDesc: "Product data downloaded successfully.",
          exportFailedTitle: "Export Failed",
          exportFailedDesc: "An error occurred during product export.",
        },
        cardTitleWithCount: "Products ({count})",
        noProductsFound: "No products found",
      },
      orders: {
        headerTitle: "Order Management",
        subtitle: "Administer and monitor customer orders",
        searchPlaceholder: "Search by order number or email...",
        filterByStatus: "Filter by status",
        allStatuses: "All Statuses",
        title: "Orders",
        tableDescription: "List of recent orders",
        table: {
          order: "Order",
          customer: "Customer",
          status: "Status",
          total: "Total",
          payment: "Payment",
          date: "Date",
          actions: "Actions",
        },
        stats: {
          total: "Total Orders",
          pending: "Pending",
          confirmed: "Confirmed",
          processing: "Processing",
          printing: "Printing",
          shipped: "Shipped",
          completed: "Completed",
          cancelled: "Cancelled",
        },
        loading: "Loading orders...",
        orderSummary: "Order Summary",
        orderManagement: "Order Management",
        updateStatus: "Update Status:",
        noItemsFound: "No items found",
        invoice: "INVOICE",
        noOrdersFound: "No orders found",
        customerInformation: "Customer Information",
        emailLabel: "Email",
        nameLabel: "Name",
        phoneLabel: "Phone",
        paymentDelivery: "Payment & Delivery",
        paymentLabel: "Payment",
        shippingLabel: "Shipping",
        transactionLabel: "Transaction ID",
        invoiceLabel: "Invoice",
        shippingAddress: "Shipping Address",
        orderItems: "Order Items",
        itemTotalLabel: "Item Total",
        qtyLabel: "Qty:",
        subtotalLabel: "Subtotal",
        taxLabel: "Tax",
        discountLabel: "Discount",
        totalLabel: "Total",
        digitalBadgePrefix: "Digital",
        customizedLabel: "Customized",
        customizationsLabel: "Customizations:",
        generating: "Generating...",
        generateInvoice: "Generate Invoice",
        customerNotesLabel: "Customer Notes:",
        statuses: {
          pending: "Pending",
          confirmed: "Confirmed",
          processing: "Processing",
          printing: "Printing",
          shipped: "Shipped",
          completed: "Completed",
          cancelled: "Cancelled",
        },
        toasts: {
          errorLoadingOrders: "Failed to load orders",
          statusUpdatedPrefix: "Order status updated to",
          updateStatusError: "Failed to update order status",
          noDesignFileTitle: "No Design File",
          noDesignFileDesc: "No design file available for this item",
          downloadStartedTitle: "Download Started",
          downloadStartedDescPrefix: "Downloading file for",
          downloadFailedTitle: "Download Failed",
          downloadFailedDesc: "Failed to download design file",
          invoiceGeneratedTitle: "Invoice Generated",
          invoiceGeneratedDescPrefix: "Invoice",
          invoiceGeneratedDescSuffix: "is ready for printing",
          invoiceGenerateError: "Failed to generate invoice",
        },
        orderDetailsTitle: "Order Details - {orderNumber}",
        orderDetailsDescription: "View and manage order information",
        na: "N/A",
        invoicePage: {
          titlePrefix: "Invoice",
          invoiceNumberLabel: "Invoice Number:",
          orderNumberLabel: "Order Number:",
          dateLabel: "Date:",
          paymentMethodLabel: "Payment Method:",
          transactionIdLabel: "Transaction ID:",
          billTo: "Bill To:",
          tableHeaders: {
            item: "Item",
            quantity: "Quantity",
            unitPrice: "Unit Price",
            total: "Total",
          },
          thankYouNote: "Thank you for your business!",
        },
      },
      payments: {
        headerTitle: "Payment Processors",
        providersTitle: "Payment Providers",
        connectionTestingTitle: "Connection Testing",
        apiTestingFrameworkTitle: "API Testing Framework",
        placeholders: {
          apiKey: "Enter API key or client ID",
          apiSecret: "Enter API secret or client secret",
          webhookUrl: "https://yoursite.com/webhooks/payments",
          webhookSecret: "Enter webhook secret",
          endpoint: "Enter {key} endpoint",
          commaSeparated: "Enter comma-separated values",
          enterKey: "Enter {key}",
          apiEndpoint: "https://api.example.com/endpoint",
          authValue: "Enter authentication value",
          headersJson: '{"X-Custom-Header": "value", "Accept": "application/json"}',
          bodyJson: '{"key": "value"}',
        },
      },
      transactions: {
        headerTitle: "Payment Transactions",
        headerSubtitle: "View and manage all payment transactions",
        filtersTitle: "Filters",
        filterByStatus: "Filter by status",
        filterByProvider: "Filter by provider",
        searchPlaceholder: "Search by order ID, transaction ID...",
      },
      users: {
        headerTitle: "User Management",
        searchPlaceholder: "Search users...",
        filterByRole: "Filter by role",
        filterByStatus: "Filter by status",
        title: "Users",
      },
      quotes: {
        headerTitle: "Quote Management",
        searchPlaceholder: "Search quotes...",
        filterByStatus: "Filter by status",
        title: "Quotes",
        responsePlaceholder: "Enter your response to the customer...",
      },
      emailSettings: {
        headerTitle: "Email Settings",
        configurationTitle: "Email Configuration",
        templatesTitle: "Email Templates",
        saveSettings: "Save Settings",
        enableEmailSending: "Enable Email Sending",
        placeholders: {
          fromName: "DeliveryPrint",
          adminEmail: "admin@yourdomain.com",
        },
      },
    },
  },
  es: {
    navigation: {
      home: "Inicio",
      products: "Productos",
      digitalProducts: "Productos Digitales",
      services: "Servicios",
      aiStudio: "Estudio IA",
      about: "Acerca de",
      contact: "Contacto",
      signIn: "Iniciar Sesión",
      signOut: "Cerrar Sesión",
      getStarted: "Comenzar",
      dashboard: "Panel",
      orders: "Pedidos",
      downloads: "Descargas",
      digitalDownloads: "Descargas Digitales",
      settings: "Configuración",
      admin: "Administrador",
      cart: "Carrito",
      checkout: "Pagar",
      supplierPortal: "Portal de Proveedores",
    },
    cart: {
      title: "Tu Carrito",
      empty: "Tu carrito está vacío",
      emptyDescription: "Agrega algunos productos a tu carrito para comenzar",
      browseProducts: "Ver Productos",
      proceedToCheckout: "Proceder al Pago",
      items: "artículos",
      removeItem: "Eliminar artículo",
      updateQuantity: "Actualizar cantidad",
      subtotal: "Subtotal",
    },
    products: {
      title: "Productos",
      description: "Descubre nuestra amplia gama de productos de impresión personalizada",
      catalogTitle: "Catálogo de Productos",
      catalogDescription: "Explora nuestra colección de productos personalizables",
      searchPlaceholder: "Buscar productos...",
      allCategories: "Todas las categorías",
      sortBy: "Ordenar por",
      sortName: "Nombre",
      sortPriceAsc: "Precio: Menor a Mayor",
      sortPriceDesc: "Precio: Mayor a Menor",
      sortNewest: "Más nuevos",
      badgeCustomizable: "Personalizable",
      buttonCustomize: "Personalizar",
      noProductsFound: "No se encontraron productos que coincidan con tus criterios",
    },
    productDetail: {
      notFoundTitle: "Producto no encontrado",
      notFoundDescription:
        "El producto que buscas no existe o ha sido eliminado.",
      backToProducts: "Volver a Productos",
      quantity: "Cantidad",
      size: "Talla",
      addToCart: "Agregar al carrito",
      save: "Guardar",
      // Texto del toast para guardado exitoso en la página de producto
      saveSuccess: "Producto guardado",
      saveSuccessDesc: "Guardado en tu biblioteca.",
      share: "Compartir",
      tabDetails: "Detalles del producto",
      tabCustomize: "Personalizar diseño",
      specificationsTitle: "Especificaciones del producto",
      materialLabel: "Material:",
      materialValue: "Calidad Premium",
      dimensionsLabel: "Dimensiones:",
      dimensionsValue: "Varía según tamaño",
      printAreaLabel: "Área de impresión:",
      printAreaValue: "Frente y reverso",
      careLabel: "Cuidado:",
      careValue: "Lavable a máquina",
      shippingInfoTitle: "Información de envío",
      productionTimeLabel: "Tiempo de producción:",
      productionTimeValue: "2-3 días hábiles",
      shippingLabel: "Envío:",
      shippingValue: "3-5 días hábiles",
      returnsLabel: "Devoluciones:",
      returnsValue: "Política de devolución de 30 días",
    },
    checkout: {
      title: "Pagar",
      subtitle: "Completa tu pedido proporcionando tu información a continuación",
      digitalOrderTitle: "Pedido de productos digitales",
      digitalOrderBadge: "Descarga digital",
      digitalOrderDescription:
        "Tus productos digitales estarán disponibles para descargar después de completar el pago.",
      completePaymentWithPayPal: "Completar pago con PayPal",
      clickPayPalButtons:
        "Haz clic en uno de los botones de PayPal para completar tu pago",
      orderTotal: "Total del pedido:",
      orderNumberLabel: "Pedido #",
      backToCheckout: "Volver al pago",
      billingTitle: "Información de facturación",
      billingDescription: "Ingresa tus datos de facturación",
      shippingTitle: "Información de envío",
      shippingDescription: "¿Dónde debemos enviar tu pedido?",
      sameAsBilling: "Igual que la dirección de facturación",
      firstName: "Nombre *",
      lastName: "Apellido *",
      email: "Correo electrónico *",
      phone: "Teléfono *",
      address: "Dirección *",
      city: "Ciudad *",
      state: "Estado/Provincia *",
      zipCode: "Código postal *",
      country: "País *",
      orderNotesLabel: "Notas del pedido (Opcional)",
      orderNotesPlaceholder: "Instrucciones especiales de entrega o detalles del pedido...",
      deliveryMethodTitle: "Método de entrega",
      deliveryMethodDescription: "Elige cómo quieres recibir tu pedido",
      paymentMethodTitle: "Método de pago",
      paymentMethodDescription: "Selecciona cómo quieres pagar tu pedido",
      orderSummaryTitle: "Resumen del pedido",
      orderSummaryDescription: "Revisa tu pedido antes de finalizar",
      subtotalLabel: "Subtotal",
      shippingLabel: "Envío",
      taxLabel: "Impuesto (13%)",
      totalLabel: "Total",
      agreeToTerms: "Acepto los Términos de servicio y la Política de privacidad",
      completeOrder: "Finalizar pedido",
      paymentMethods: {
        wompi: { name: "Tarjeta de crédito/débito", description: "Visa, Mastercard, American Express" },
        paypal: { name: "PayPal", description: "Cuenta de PayPal" },
        stripe: { name: "Stripe", description: "Tarjeta de crédito/débito" },
        cash: { name: "Pago contra entrega", description: "Paga al recibir" },
      },
      shippingMethods: {
        standard: { name: "Envío regular", description: "5-7 días hábiles" },
        express: { name: "Envío prioritario", description: "3-5 días hábiles" },
        overnight: { name: "Envío urgente", description: "1-2 días hábiles" },
        pickup: { name: "Recoger en tienda", description: "Recoge en nuestra tienda" },
        download: { name: "Descarga digital", description: "Descarga inmediata después del pago" },
      },
    },
    home: {
      heroTitle: "Tu Visión, Impresa.",
      heroSubtitle:
        "Impresión personalizada de alta calidad para todas tus necesidades. Desde prendas hasta gran formato, hacemos realidad tus ideas.",
      exploreProducts: "Explorar Productos",
      servicesTitle: "Nuestros Servicios",
      featuredProductsTitle: "Productos Destacados",
      // Sección de CTA inferior en la página de inicio
      ctaTitle: "¿Listo para imprimir tus ideas?",
      ctaSubtitle:
        "Comienza con nuestras herramientas de diseño fáciles de usar o contáctanos para una cotización personalizada.",
      ctaGetQuote: "Obtener Cotización",
      errors: {
        failedToLoadFeatured: "No se pudieron cargar los productos destacados. Por favor intenta más tarde.",
        displayingSample: "Mostrando productos de ejemplo.",
      },
      noFeatured: "No se encontraron productos destacados. Mostrando productos de ejemplo.",
      noDescription: "Sin descripción disponible.",
    },
    orders: {
      title: "Pedidos",
      myOrders: "Mis Pedidos",
    },
    dashboard: {
      title: "Panel",
    },
    settings: {
      title: "Configuración",
    },
    services: {
      all: "Todos los Servicios",
      digitalPrinting: "Impresión Digital",
      largeFormat: "Gran Formato",
      eventStands: "Stands para Eventos",
      illuminatedSigns: "Letreros Iluminados",
      designStudio: "Estudio de Diseño",
      digitalPrintingDesc: "Impresiones de alta resolución para folletos, volantes y diseños personalizados.",
      largeFormatDesc: "Banners, carteles y letreros para máximo impacto.",
      designStudioDesc: "Crea diseños increíbles con nuestras herramientas impulsadas por IA o ayuda profesional.",
      page: {
        heroTitle: "Servicios Profesionales de Impresión",
        heroSubtitle: "Soluciones completas de impresión para tu negocio: desde impresión digital hasta señalización iluminada",
        ctaGetStarted: "Comenzar",
        ctaRequestQuote: "Solicitar Cotización",
        sectionTitle: "Nuestros Servicios",
        sectionSubtitle: "Elige entre nuestra gama integral de servicios de impresión, diseñados para necesidades específicas",
        featuresLabel: "Características:",
        startingFrom: "Desde",
        explore: "Explorar",
        whyChooseTitle: "¿Por qué elegir nuestros servicios?",
        whyChooseSubtitle: "Nos comprometemos a ofrecer calidad y servicio excepcionales para todas tus necesidades de impresión",
        benefitQuality: "Garantía de Calidad",
        benefitSpeed: "Entrega Rápida",
        benefitPro: "Servicio Profesional",
        howItWorksTitle: "Cómo Funciona",
        howItWorksSubtitle: "Pasos sencillos para completar tu proyecto de impresión",
        steps: {
          chooseService: "Elegir Servicio",
          descChooseService: "Selecciona el servicio de impresión que se ajuste a tus necesidades",
          configureUpload: "Configurar y Subir",
          descConfigureUpload: "Personaliza opciones y sube tus archivos de diseño",
          reviewOrder: "Revisar y Comprar",
          descReviewOrder: "Revisa los detalles y completa el pago",
          productionDelivery: "Producción y Entrega",
          descProductionDelivery: "Imprimimos y entregamos tu pedido a tiempo",
        },
        ctaTitle: "¿Listo para comenzar tu proyecto?",
        ctaSubtitle: "Servicios profesionales de impresión con tiempos rápidos y precios competitivos",
        ctaStartDigitalPrinting: "Comenzar Impresión Digital",
        ctaRequestCustomQuote: "Solicitar Cotización Personalizada",
      },
      largeFormatPage: {
        headerTitle: "Impresión en Gran Formato",
        headerSubtitle: "Banners, carteles y productos especiales de gran escala",
        customDesignReady: "Diseño personalizado listo para imprimir",
        customDesignCardTitle: "Tu Diseño Personalizado",
        manuallyCreated: "Creado Manualmente",
        readyForPrinting: "Listo para Imprimir",
        selectProductType: "Seleccionar Tipo de Producto",
        weatherResistant: "Resistente a la intemperie",
        baseLabel: "Base:",
        sizeConfigTitle: "Configuración de Tamaño",
        width: "Ancho",
        height: "Alto",
        standardSize: "Tamaño estándar",
        totalArea: "Área total",
        squareMeters: "metros cuadrados",
        quantity: "Cantidad",
        specialInstructionsLabel: "Instrucciones Especiales (Opcional)",
        specialInstructionsPlaceholder: "Ojales, dobladillo, requisitos de montaje, etc.",
        uploadCreateTitle: "Subir o Crear tu Diseño",
        dropFilesHere: "Arrastra tus archivos aquí",
        supportFormats: "Formatos soportados: PDF, PNG, JPG, AI, PSD (Máx 100MB)",
        chooseFiles: "Elegir Archivos",
        orCreateCustomDesign: "O crea un diseño personalizado:",
        customizeDesign: "Personalizar Diseño",
        designLoaded: "Diseño Cargado",
        designReady: "Tu diseño personalizado está listo.",
        editDesign: "Editar Diseño",
        guidelinesTitle: "Guías para Gran Formato:",
        guidelines: {
          bullet1: "• Mínimo 150 DPI al tamaño final",
          bullet2: "• Se prefieren archivos vectoriales por su escalabilidad",
          bullet3: "• Incluye sangrado para impresión al borde",
          bullet4: "• Considera la distancia de visualización para el tamaño del texto",
        },
        orderSummaryTitle: "Resumen de Pedido",
        size: "Tamaño:",
        area: "Área:",
        design: "Diseño:",
        custom: "Personalizado",
        unitPrice: "Precio Unitario:",
        areaCost: "Costo por Área:",
        total: "Total:",
        requestDetailedQuote: "Solicitar Cotización Detallada",
        productionInfoTitle: "Información de Producción",
        turnaround: "Tiempo de entrega:",
        turnaroundValue: "2-3 días hábiles",
        material: "Material:",
        materialValue: "Vinilo de 13oz",
        finishing: "Acabado:",
        finishingValue: "Ojales disponibles",
        installation: "Instalación:",
        installationValue: "Disponible",
        sqMetersShort: "m²",
        products: {
          banner: {
            name: "BANNER",
            description: "Banners de vinilo duraderos, perfectos para publicidad exterior y eventos",
            unit: "MTS",
            priceUnit: "por metro cuadrado",
          },
          troquelados: {
            name: "TROQUELADOS",
            description: "Formas troqueladas de precisión y cortes personalizados",
            unit: "pulgadas",
            priceUnit: "por pieza",
          },
        },
      },
      // Páginas específicas de servicios
      digitalPrintingPage: {
        headerTitle: "Servicios de Impresión Digital",
        headerSubtitle: "Impresión de formato estándar de alta calidad para todas tus necesidades",
        aiGeneratedLabel: "Diseño Generado por IA",
        customDesignLabel: "Diseño Personalizado",
        readyForPrinting: "Listo para Imprimir",
        yourAIGeneratedDesign: "Tu Diseño Generado por IA",
        yourCustomDesign: "Tu Diseño Personalizado",
        manuallyCreated: "Creado Manualmente",
        selectMaterial: "Seleccionar Material",
        doubleSided: "Doble cara",
        sizeOptionsTitle: "Tamaño y Opciones",
        materialSize: "Tamaño del Material",
        printSides: "Lados de Impresión",
        singleSided: "Una cara",
        quantity: "Cantidad",
        uploadCreateTitle: "Sube o Crea tu Diseño",
        dropFilesHere: "Arrastra tus archivos aquí",
        supportFormatsShort: "Formatos soportados: PDF, PNG, JPG, AI, PSD, ZIP (Máx 50MB)",
        chooseFiles: "Elegir Archivos",
        uploadedFilesLabel: "Archivos Subidos:",
        orCreateCustomDesign: "O crea un diseño personalizado:",
        customizeDesign: "Personalizar Diseño",
        customUpload: "Carga Personalizada",
        designLoaded: "Diseño Cargado",
        designReady: "Tu diseño personalizado está listo.",
        editDesign: "Editar Diseño",
        replace: "Reemplazar",
        edit: "Editar",
        designGuidelinesTitle: "Guías de Diseño:",
        guidelines: {
          bullet1: "• Resolución mínima de 300 DPI",
          bullet2: "• Incluye 0.125\" de sangrado para diseños a borde",
          bullet3: "• Se prefiere modo de color CMYK",
        },
        orderSummaryTitle: "Resumen de Pedido",
        aiGenerated: "Generado por IA",
        requestCustomQuote: "Solicitar Cotización Personalizada",
        products: {
          "foldcote-14": {
            name: "FOLDCOTE 14",
            description: "Papel recubierto premium con excelente calidad de impresión y durabilidad",
          },
          adhesivo: {
            name: "ADHESIVO",
            description: "Stickers de vinilo de alta calidad con adhesivo fuerte",
          },
          couche: {
            name: "COUCHE",
            description: "Papel couché liso perfecto para impresión a color de alta calidad",
          },
          bond: {
            name: "BOND",
            description: "Papel bond estándar para necesidades de impresión diaria",
          },
          "etiqueta-especial": {
            name: "ETIQUETA ESPECIAL",
            description: "Etiquetas especiales premium para aplicaciones profesionales",
          },
          vinyl: {
            name: "VINYL BANNER",
            description: "Material de vinilo duradero ideal para señalización exterior y impresiones de gran formato",
          },
          troquelate: {
            name: "TROQUELATE",
            description: "Material especial troquelado para formas personalizadas y aplicaciones profesionales",
          },
          canvas: {
            name: "CANVAS",
            description: "Lienzo de alta calidad ideal para impresiones artísticas y exhibiciones de gran formato",
          },
        },
      },
      eventStandsPage: {
        headerTitle: "Stands y Exhibidores para Eventos",
        headerSubtitle:
          "Exhibidores profesionales, stands para ferias y estructuras portátiles para destacar tu marca en cualquier evento",
        badges: {
          freeShipping: "Envío Gratuito",
          quickTurnaround: "Entrega Rápida",
          qualityGuarantee: "Garantía de Calidad",
        },
        categories: {
          displayStands: "Exhibidores",
          bannerDisplays: "Exhibidores de Banner",
          tradeShow: "Feria Comercial",
          eventBackdrops: "Fondos para Eventos",
        },
        selectStandTitle: "Selecciona tu Stand para Evento",
        selectStandDescription: "Elige entre nuestras soluciones profesionales de exhibición",
        productType: "Tipo de Producto",
        sizeConfig: "Tamaño y Configuración",
        dimensions: "Dimensiones:",
        quantity: "Cantidad",
        designRequirements: "Requisitos de Diseño",
        designRequirementsPlaceholder:
          "Describe tus requisitos de diseño, colores, logos, texto, etc.",
        rushOrderLabel: "Pedido Urgente (+50% de cargo)",
        featuresLabel: "Características:",
        orderSummaryTitle: "Resumen de Pedido",
        basePrice: "Precio Base",
        rushOrderFee: "Cargo por Urgencia (50%)",
        total: "Total",
        buttons: {
          addToCart: "Agregar al Carrito",
          customizeDesign: "Personalizar Diseño",
          getCustomQuote: "Obtener Cotización Personalizada",
          needHelpQuote: "¿Necesitas ayuda? Solicita Cotización para Eventos",
        },
        products: {
          "popup-stands": {
            name: "Exhibidores Pop-up",
            description:
              "Exhibidores portátiles y fáciles de armar, perfectos para ferias y eventos",
            features: {
              item1: "Ensamblaje sin herramientas",
              item2: "Estructura de aluminio liviano",
              item3: "Incluye estuche de transporte",
              item4: "Tela resistente a arrugas",
            },
          },
          "banner-stands": {
            name: "Stands de Banner",
            description:
              "Stands retráctiles para presentaciones profesionales y exhibiciones de marketing",
            features: {
              item1: "Mecanismo retráctil",
              item2: "Altura ajustable",
              item3: "Estuche acolchado",
              item4: "Cambio fácil de gráfico",
            },
          },
          "trade-show-displays": {
            name: "Exhibidores para Ferias",
            description: "Soluciones completas de stands con componentes modulares",
            features: {
              item1: "Diseño modular",
              item2: "Opciones de iluminación LED",
              item3: "Compartimentos de almacenamiento",
              item4: "Montaje profesional",
            },
          },
          "backdrop-stands": {
            name: "Stands de Backdrop",
            description:
              "Fondos de ‘step and repeat’ ideales para eventos, fotografías y branding",
            features: {
              item1: "Estructura telescópica",
              item2: "Tela antiarrugas",
              item3: "Fácil ensamblaje",
              item4: "Estuche portátil",
            },
          },
        },
      },
      illuminatedSignsPage: {
        headerTitle: "Letreros Iluminados",
        headerSubtitle:
          "Soluciones profesionales de señalización iluminada para hacer que tu negocio brille día y noche con tecnología LED eficiente",
        badges: {
          energyEfficient: "Eficiencia Energética",
          highVisibility: "Alta Visibilidad",
          impact247: "Impacto 24/7",
        },
        selectTitle: "Selecciona tu Letrero Iluminado",
        selectDescription: "Elige entre nuestras opciones profesionales de señalización iluminada",
        signType: "Tipo de Letrero",
        sizeConfig: "Tamaño y Configuración",
        dimensions: "Dimensiones:",
        quantity: "Cantidad",
        colorPreference: "Preferencia de Color",
        colorPreferencePlaceholder: "Ej.: Blanco cálido, Blanco frío, Rojo, Azul, etc.",
        designRequirements: "Requisitos de Diseño",
        designRequirementsPlaceholder: "Describe tu texto, logos, gráficos, requisitos de montaje, etc.",
        installationLabel: "Instalación Profesional (+$200)",
        rushOrderLabel: "Pedido Urgente (+50% de cargo)",
        featuresLabel: "Características:",
        products: {
          "led-channel-letters": {
            name: "Letras LED de Canal",
            description:
              "Letras iluminadas 3D premium con iluminación LED para máxima visibilidad e impacto",
            features: {
              item1: "Letras dimensionales 3D",
              item2: "LEDs eficientes energéticamente",
              item3: "Resistente al clima",
              item4: "Colores personalizados disponibles",
            },
            category: "Letras de Canal",
            unit: "por letra",
          },
          "backlit-signs": {
            name: "Letreros Retroiluminados",
            description:
              "Letreros profesionales retroiluminados con iluminación uniforme para escaparates y negocios",
            features: {
              item1: "Retroiluminación LED uniforme",
              item2: "Material de cara translúcido",
              item3: "Marco de aluminio",
              item4: "Instalación fácil",
            },
            category: "Letreros Retroiluminados",
            unit: "por letrero",
          },
          "light-box-signs": {
            name: "Letreros de Caja de Luz",
            description:
              "Letreros de caja de luz tradicionales con tecnología LED moderna para iluminación brillante y uniforme",
            features: {
              item1: "Tiras de luz LED",
              item2: "Cara acrílica",
              item3: "Marco de apertura rápida",
              item4: "Montaje en pared o techo",
            },
            category: "Cajas de Luz",
            unit: "por letrero",
          },
          "neon-style-led": {
            name: "LED Estilo Neón",
            description:
              "Tiras LED modernas que replican el neón tradicional con eficiencia energética",
            features: {
              item1: "Tiras LED flexibles",
              item2: "Múltiples opciones de color",
              item3: "Regulable",
              item4: "Instalación fácil",
            },
            category: "LED Neón",
            unit: "por pie lineal",
          },
          "digital-display-signs": {
            name: "Letreros de Pantalla Digital",
            description:
              "Pantallas LED de alta resolución para contenido dinámico y máximo impacto visual",
            features: {
              item1: "Resolución Full HD",
              item2: "Gestión remota de contenido",
              item3: "Opciones resistentes al clima",
              item4: "Software de programación",
            },
            category: "Pantallas Digitales",
            unit: "por pantalla",
          },
          "cabinet-signs": {
            name: "Letreros de Gabinete",
            description:
              "Letreros de gabinete iluminados con apariencia profesional para negocios y escaparates",
            features: {
              item1: "Construcción de aluminio",
              item2: "Iluminación LED",
              item3: "Paneles translúcidos",
              item4: "Instalación profesional",
            },
            category: "Letreros de Gabinete",
            unit: "por letrero",
          },
        },
      },
    },

    admin: {
      nav: {
        dashboard: "Panel",
        products: "Productos",
        orders: "Pedidos",
        payments: "Pagos",
        transactions: "Transacciones de Pago",
        users: "Usuarios",
        quotes: "Cotizaciones",
        messages: "Mensajes",
        translations: "Traducciones",
        settings: "Configuración",
        emailSettings: "Configuración de Correo",
      },
      // Descripciones para los elementos de navegación del administrador
      navDescriptions: {
        dashboard: "Descripción general de tu sistema",
        products: "Administra tus productos",
        orders: "Ver y administrar pedidos",
        payments: "Procesadores de pago y transacciones",
        transactions: "Ver todas las transacciones de pago",
        users: "Administrar clientes",
        quotes: "Gestionar solicitudes de cotización",
        messages: "Tickets de soporte al cliente",
        translations: "Revisar y administrar traducciones de la interfaz",
        settings: "Configurar ajustes del sistema",
        emailSettings: "Configurar proveedores y plantillas de correo",
      },
      layout: {
        panelTitle: "Panel de Administración",
        accessDeniedTitle: "Acceso Denegado",
        accessDeniedDesc: "No tienes permiso para acceder al panel de administración.",
        goToDashboard: "Ir al Panel",
        backToSite: "Regresar al Sitio",
        account: "Cuenta",
        myAccount: "Mi Cuenta",
        signOut: "Cerrar Sesión",
      },
      dashboard: {
        headerTitle: "Panel",
        headerSubtitle: "Bienvenido al panel de administración de DeliveryPrint",
        statCards: {
          totalRevenue: "Ingresos Totales",
          totalOrders: "Pedidos Totales",
          totalUsers: "Usuarios Totales",
          totalProducts: "Productos Totales",
        },
        quickStats: {
          pendingOrders: "Pedidos Pendientes",
          completedOrders: "Pedidos Completados",
          pendingQuotes: "Cotizaciones Pendientes",
          activeUsers: "Usuarios Activos",
        },
      },
      products: {
        headerTitle: "Gestión de Productos",
        headerDescription: "Administra tu catálogo de productos",
        searchPlaceholder: "Buscar productos...",
        filterByCategory: "Filtrar por categoría",
        allCategories: "Todas las categorías",
        title: "Productos",
        tableDescription: "Administra tu inventario de productos",
        table: {
          product: "Producto",
          category: "Categoría",
          price: "Precio",
          status: "Estado",
          created: "Creado",
          actions: "Acciones",
        },
        aria: {
          selectAll: "Seleccionar todos los productos",
          selectProduct: "Seleccionar producto {name}",
        },
        labels: {
          featured: "Destacado",
        },
        statuses: {
          active: "Activo",
          inactive: "Inactivo",
        },
        na: "—",
        importDialog: {
          triggerLabel: "Importar",
          title: "Importar productos desde CSV",
          description: "Sube un archivo CSV para crear o actualizar productos.",
          csvFileLabel: "Archivo CSV",
          uploadButton: "Subir CSV",
          csvGuidelines:
            "Tu CSV debe contener columnas como `id` (opcional para actualizaciones), `name`, `description`, `price`, `category`, `image`, `is_active` (true/false), `is_featured` (true/false).",
        },
        exportMenu: {
          triggerLabel: "Exportar",
          exportAll: "Exportar todos los productos",
          exportSelectedWithCount: "Exportar seleccionados ({count})",
        },
        addButtonLabel: "Agregar Producto",
        editDialog: {
          titleEdit: "Editar Producto",
          titleAddNew: "Agregar Nuevo Producto",
          descEdit: "Actualizar información del producto",
          descAddNew: "Crear un nuevo producto para tu catálogo",
          buttons: {
            update: "Actualizar Producto",
            create: "Crear Producto",
          },
        },
        form: {
          imageLabel: "Imagen del Producto",
          imageUrlLabel: "URL de la Imagen",
          imageUrlPlaceholder: "https://ejemplo.com/imagen.jpg",
          productNameLabel: "Nombre del Producto *",
          priceLabel: "Precio *",
          descriptionLabel: "Descripción",
          categoryLabel: "Categoría",
          categoryPlaceholder: "p. ej., Ropa, Accesorios",
          activeLabel: "Activo",
          featuredLabel: "Destacado",
          imageSelectedInfo:
            "La imagen se cargará desde el archivo seleccionado. La entrada manual de URL está deshabilitada.",
        },
        imageUpload: {
          clickToUpload: "Haz clic para subir",
          orDragAndDrop: "o arrastra y suelta",
          supportedFormats: "SVG, PNG, JPG o GIF (MÁX. 800x400px)",
          removeImage: "Eliminar Imagen",
          previewAlt: "Vista previa del producto",
          uploading: "Subiendo imagen...",
        },
        toasts: {
          errorLoadingProducts: "Error al cargar productos",
          imageUploadedTitle: "Imagen subida",
          imageUploadedDesc: "La imagen del producto se subió correctamente.",
          imageUploadFailedTitle: "Error al subir imagen",
          imageUploadFailedDesc: "Ocurrió un error durante la subida de la imagen.",
          submissionFailedTitle: "Error de envío",
          submissionFailedDesc: "La subida de la imagen falló, por favor intenta de nuevo.",
          productUpdated: "Producto actualizado correctamente",
          productCreated: "Producto creado correctamente",
          saveProductFailed: "Error al guardar el producto",
          deleteConfirm: "¿Estás seguro de que deseas eliminar este producto?",
          productDeleted: "Producto eliminado correctamente",
          deleteProductFailed: "Error al eliminar el producto",
          noFileSelectedTitle: "No se seleccionó archivo",
          noFileSelectedDesc: "Por favor selecciona un archivo CSV para importar.",
          importingProductsTitle: "Importando productos",
          importingProductsDesc: "Subiendo y procesando tu archivo CSV...",
          importCompleteTitle: "Importación completa",
          importCompleteDesc:
            "Se importaron {created} productos nuevos y se actualizaron {updated} productos existentes.",
          importFailedTitle: "Error de importación",
          importFailedDesc: "Ocurrió un error durante la importación de productos.",
          exportingProductsTitle: "Exportando productos",
          exportingProductsDesc: "Preparando tus datos de productos para descargar...",
          noProductsSelectedTitle: "No hay productos seleccionados",
          noProductsSelectedDesc:
            "Selecciona productos para exportar, o elige \"Exportar todos\".",
          exportCompleteTitle: "Exportación completa",
          exportCompleteDesc: "Los datos de productos se descargaron correctamente.",
          exportFailedTitle: "Error de exportación",
          exportFailedDesc: "Ocurrió un error durante la exportación de productos.",
        },
        cardTitleWithCount: "Productos ({count})",
        noProductsFound: "No se encontraron productos",
      },
      orders: {
        headerTitle: "Gestión de Pedidos",
        subtitle: "Administra y monitorea pedidos de clientes",
        searchPlaceholder: "Buscar por número de pedido o correo...",
        filterByStatus: "Filtrar por estado",
        allStatuses: "Todos los estados",
        title: "Pedidos",
        tableDescription: "Listado de pedidos recientes",
        table: {
          order: "Pedido",
          customer: "Cliente",
          status: "Estado",
          total: "Total",
          payment: "Pago",
          date: "Fecha",
          actions: "Acciones",
        },
        stats: {
          total: "Pedidos Totales",
          pending: "Pendiente",
          confirmed: "Confirmado",
          processing: "Procesando",
          printing: "Imprimiendo",
          shipped: "Enviado",
          completed: "Completado",
          cancelled: "Cancelado",
        },
        loading: "Cargando pedidos...",
        orderSummary: "Resumen del Pedido",
        orderManagement: "Gestión del Pedido",
        updateStatus: "Actualizar Estado:",
        noItemsFound: "No se encontraron artículos",
        invoice: "FACTURA",
        noOrdersFound: "No se encontraron pedidos",
        customerInformation: "Información del Cliente",
        emailLabel: "Correo",
        nameLabel: "Nombre",
        phoneLabel: "Teléfono",
        paymentDelivery: "Pago y Envío",
        paymentLabel: "Pago",
        shippingLabel: "Envío",
        transactionLabel: "ID de Transacción",
        invoiceLabel: "Factura",
        shippingAddress: "Dirección de Envío",
        orderItems: "Artículos del Pedido",
        itemTotalLabel: "Total del Artículo",
        qtyLabel: "Cant:",
        subtotalLabel: "Subtotal",
        taxLabel: "Impuesto",
        discountLabel: "Descuento",
        totalLabel: "Total",
        digitalBadgePrefix: "Digital",
        customizedLabel: "Personalizado",
        customizationsLabel: "Personalizaciones:",
        generating: "Generando...",
        generateInvoice: "Generar Factura",
        customerNotesLabel: "Notas del Cliente:",
        statuses: {
          pending: "Pendiente",
          confirmed: "Confirmado",
          processing: "Procesando",
          printing: "Imprimiendo",
          shipped: "Enviado",
          completed: "Completado",
          cancelled: "Cancelado",
        },
        toasts: {
          errorLoadingOrders: "Error al cargar pedidos",
          statusUpdatedPrefix: "Estado del pedido actualizado a",
          updateStatusError: "Error al actualizar el estado del pedido",
          noDesignFileTitle: "Sin archivo de diseño",
          noDesignFileDesc: "No hay archivo de diseño disponible para este artículo",
          downloadStartedTitle: "Descarga iniciada",
          downloadStartedDescPrefix: "Descargando archivo para",
          downloadFailedTitle: "Descarga fallida",
          downloadFailedDesc: "Error al descargar el archivo de diseño",
          invoiceGeneratedTitle: "Factura generada",
          invoiceGeneratedDescPrefix: "La factura",
          invoiceGeneratedDescSuffix: "está lista para imprimir",
          invoiceGenerateError: "Error al generar la factura",
        },
        orderDetailsTitle: "Detalles del Pedido - {orderNumber}",
        orderDetailsDescription: "Ver y administrar la información del pedido",
        na: "N/A",
        invoicePage: {
          titlePrefix: "Factura",
          invoiceNumberLabel: "Número de factura:",
          orderNumberLabel: "Número de pedido:",
          dateLabel: "Fecha:",
          paymentMethodLabel: "Método de pago:",
          transactionIdLabel: "ID de transacción:",
          billTo: "Facturar a:",
          tableHeaders: {
            item: "Artículo",
            quantity: "Cantidad",
            unitPrice: "Precio unitario",
            total: "Total",
          },
          thankYouNote: "¡Gracias por su compra!",
        },
      },
      payments: {
        headerTitle: "Procesadores de Pago",
        providersTitle: "Proveedores de Pago",
        connectionTestingTitle: "Pruebas de Conexión",
        apiTestingFrameworkTitle: "Marco de Pruebas de API",
        placeholders: {
          apiKey: "Ingresa la clave API o client ID",
          apiSecret: "Ingresa el secreto API o client secret",
          webhookUrl: "https://tusitio.com/webhooks/pagos",
          webhookSecret: "Ingresa el secreto del webhook",
          endpoint: "Ingresa el endpoint de {key}",
          commaSeparated: "Ingresa valores separados por comas",
          enterKey: "Ingresa {key}",
          apiEndpoint: "https://api.ejemplo.com/endpoint",
          authValue: "Ingresa el valor de autenticación",
          headersJson: '{"X-Custom-Header": "valor", "Accept": "application/json"}',
          bodyJson: '{"key": "valor"}',
        },
      },
      transactions: {
        headerTitle: "Transacciones de Pago",
        headerSubtitle: "Ver y administrar todas las transacciones de pago",
        filtersTitle: "Filtros",
        filterByStatus: "Filtrar por estado",
        filterByProvider: "Filtrar por proveedor",
        searchPlaceholder: "Buscar por ID de pedido, ID de transacción...",
      },
      users: {
        headerTitle: "Gestión de Usuarios",
        searchPlaceholder: "Buscar usuarios...",
        filterByRole: "Filtrar por rol",
        filterByStatus: "Filtrar por estado",
        title: "Usuarios",
      },
      quotes: {
        headerTitle: "Gestión de Cotizaciones",
        searchPlaceholder: "Buscar cotizaciones...",
        filterByStatus: "Filtrar por estado",
        title: "Cotizaciones",
        responsePlaceholder: "Ingresa tu respuesta para el cliente...",
      },
      emailSettings: {
        headerTitle: "Configuración de Correo",
        configurationTitle: "Configuración de Email",
        templatesTitle: "Plantillas de Email",
        saveSettings: "Guardar Configuración",
        enableEmailSending: "Habilitar envío de correo",
        placeholders: {
          fromName: "DeliveryPrint",
          adminEmail: "admin@tudominio.com",
        },
      },
    },
    auth: {
      signIn: "Iniciar Sesión",
      signOut: "Cerrar Sesión",
      getStarted: "Comenzar",
      welcomeBack: "Bienvenido de nuevo",
      enterCredentials: "Ingresa tus credenciales para acceder a tu cuenta",
      emailLabel: "Correo electrónico",
      passwordLabel: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      signingIn: "Iniciando sesión...",
      createAccount: "Crear cuenta",
      noAccount: "¿No tienes una cuenta?",
    },
    supplier: {
      portal: "Portal de Proveedores",
    },
    users: {
      title: "Usuarios",
    },
    quotes: {
      title: "Cotizaciones",
    },
    payment: {
      modal: {
        title: "Detalles de Pago"
      },
      testMode: {
        title: "Modo de Prueba",
        description: "Modo de prueba Wompi - Usa CVV para simular diferentes escenarios:"
      },
      testCard: {
        declined: "El pago será rechazado",
        othersSuccess: "El pago será exitoso",
        success: "El pago será exitoso"
      },
      security: {
        sslEncrypted: "Cifrado SSL",
        pciCompliant: "Cumple PCI",
        notice: "Tu información de pago está segura y cifrada"
      },
      form: {
        cardNumber: "Número de Tarjeta",
        month: "Mes",
        year: "Año",
        cvv: "CVV",
        cardholderName: "Nombre del Titular",
        country: "País",
        region: "Región"
      },
      validation: {
        cardNumber: "Por favor ingresa un número de tarjeta válido",
        expiry: "Por favor ingresa una fecha de vencimiento válida",
        cvv: "Por favor ingresa un CVV válido",
        cardholderName: "Por favor ingresa el nombre del titular",
      },
      summary: {
        totalToPay: "Total a Pagar:"
      },
      processing: "Procesando",
      payButton: "Pagar",
      error: {
        title: "Error de Pago",
        processingFailed: "El procesamiento del pago falló. Por favor intenta de nuevo."
      },
      success: {
        title: "Pago Exitoso",
        transactionId: "ID de Transacción"
      },
      "3ds": {
        processing: {
          title: "Procesando Pago",
          message: "Por favor espere mientras verificamos su pago...",
        },
        success: {
          title: "¡Pago Exitoso!",
          message: "Su pago ha sido procesado exitosamente.",
        },
        failed: {
          title: "Pago Fallido",
          message: "Su pago no pudo ser procesado.",
        },
        error: {
          title: "Error de Pago",
          message: "Hubo un error procesando su pago.",
        },
        verifying: "Verificando pago con el banco...",
        viewOrder: "Ver Detalles del Pedido",
        viewAllOrders: "Ver Todos los Pedidos",
        tryAgain: "Intentar de Nuevo",
        continueShopping: "Continuar Comprando",
        transactionId: "ID de Transacción",
      },
      errors: {
        insufficientFunds: "Fondos insuficientes en su cuenta",
        declined: "Tarjeta rechazada por su banco",
        expiredCard: "Su tarjeta ha expirado",
        limitExceeded: "Límite de transacción excedido",
        restrictedCard: "Tarjeta restringida",
        generic: "Pago fallido. Por favor intente de nuevo.",
      },
    },
    common: {
      loading: "Cargando...",
      error: "Error",
      success: "Éxito",
      cancel: "Cancelar",
      save: "Guardar",
      delete: "Eliminar",
      edit: "Editar",
      add: "Agregar",
      remove: "Quitar",
      search: "Buscar",
      filter: "Filtrar",
      sort: "Ordenar",
      next: "Siguiente",
      previous: "Anterior",
      submit: "Enviar",
      close: "Cerrar",
      learnMore: "Saber Más",
      startDesigning: "Comenzar a Diseñar",
      addToCart: "Agregar al Carrito",
      labels: {
        size: "Tamaño:",
        print: "Impresión:",
        quantity: "Cantidad",
        design: "Diseño:",
        unitPrice: "Precio Unitario:",
        total: "Total:",
      },
      from: "Desde",
      quote: "Cotización",
      ready: "Listo",
      loginRequired: {
        title: "Se requiere iniciar sesión",
        description: "Por favor inicia sesión para crear diseños personalizados.",
      },
      toast: {
        addedToCartTitle: "Agregado al Carrito",
        addedToCartDescSuffix: "ha sido agregado a tu carrito.",
        designSavedTitle: "Diseño Guardado",
        designSavedDesc: "Tu diseño personalizado ha sido guardado y se aplicará a tu pedido.",
      },
    },
  },
}

// AI Studio page translations (top-level)
;(translations as any).en.aiStudioPage = {
  headerTitle: "AI Design Studio",
  headerSubtitle: "Harness the power of AI to create stunning designs for your print-on-demand products",
  services: {
    logo: { title: "AI Logo Generator", description: "Create unique, professional logos for your brand" },
    image: { title: "AI Image Generator", description: "Generate custom images for your designs" },
    font: { title: "AI Font Generator", description: "Design unique typography for your brand" },
  },
  getStarted: "Get Started",
  howItWorksTitle: "How It Works",
  steps: {
    chooseService: { title: "Choose Your Service", desc: "Select from logo, image, or font generation" },
    describeVision: { title: "Describe Your Vision", desc: "Enter a detailed prompt for AI generation" },
    downloadUse: { title: "Download & Use", desc: "Purchase and download in multiple formats" },
  },
}

;(translations as any).es.aiStudioPage = {
  headerTitle: "Estudio de Diseño con IA",
  headerSubtitle: "Aprovecha el poder de la IA para crear diseños impresionantes para tus productos de impresión bajo demanda",
  services: {
    logo: { title: "Generador de Logos con IA", description: "Crea logos únicos y profesionales para tu marca" },
    image: { title: "Generador de Imágenes con IA", description: "Genera imágenes personalizadas para tus diseños" },
    font: { title: "Generador de Tipografías con IA", description: "Diseña tipografías únicas para tu marca" },
  },
  getStarted: "Comenzar",
  howItWorksTitle: "Cómo Funciona",
  steps: {
    chooseService: { title: "Elige tu Servicio", desc: "Selecciona entre generación de logo, imagen o tipografía" },
    describeVision: { title: "Describe tu Visión", desc: "Ingresa un prompt detallado para la generación con IA" },
    downloadUse: { title: "Descargar y Usar", desc: "Compra y descarga en múltiples formatos" },
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  // Load language from localStorage on mount
  useEffect(() => {
    if (typeof window !== "undefined") {
      try {
        const savedLanguage = localStorage.getItem("language") as Language
        if (savedLanguage && (savedLanguage === "en" || savedLanguage === "es")) {
          setLanguage(savedLanguage)
        } else {
          // Detect browser language
          const browserLang = navigator.language.toLowerCase()
          if (browserLang.startsWith("es")) {
            setLanguage("es")
          } else {
            setLanguage("en")
          }
        }
      } catch (error) {
        console.error("Error loading language from localStorage:", error)
        setLanguage("en")
      }
    }
  }, [])

  // Save language to localStorage when it changes
  useEffect(() => {
    if (typeof window !== "undefined") {
      try {
        localStorage.setItem("language", language)
      } catch (error) {
        console.error("Error saving language to localStorage:", error)
      }
    }
  }, [language])

  // Translation function
  const t = (key: string): string => {
    try {
      const keys = key.split(".")
      let value: any = translations[language]

      for (const k of keys) {
        if (value && typeof value === "object" && k in value) {
          value = value[k]
        } else {
          // Fallback to English if key not found
          value = translations.en
          for (const fallbackKey of keys) {
            if (value && typeof value === "object" && fallbackKey in value) {
              value = value[fallbackKey]
            } else {
              return key // Return key if not found in fallback
            }
          }
          break
        }
      }

      return typeof value === "string" ? value : key
    } catch (error) {
      console.error("Error in translation function:", error)
      return key
    }
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
